# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# --- Path to dotfiles directory ---
export DOTFILES="$HOME/dotfiles"

# --- Load external plugins & theme (Homebrew) ---

# Powerlevel10k theme
if [ -f /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme ]; then
  source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
fi

# zsh-autosuggestions
if [ -f /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
  source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

# --- Load Powerlevel10k configuration ---
# This file is generated by running `p10k configure`
if [ -f "$HOME/.p10k.zsh" ]; then
  source "$HOME/.p10k.zsh"
fi

# --- Load modular configuration files ---
# Includes aliases, exports, functions, keybindings, etc.
if [ -d "$DOTFILES/zsh/config" ]; then
  for file in "$DOTFILES"/zsh/config/*.zsh; do
    [ -f "$file" ] && source "$file"
  done
fi
